owner: TebbaaX
repo: DownTime-Score

sites:
  - name: CNSS
    url: https://www.cnss.ma

status-website:
  baseUrl: /DownTime-Score
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
