owner: TebbaaX
repo: DownTime-Score

sites:
  - name: CNSS
    url: https://www.cnss.ma
  - name: Data
    url: http://data.gov.ma
  - name: Douanes
    url: http://www.douane.gov.ma
  - name: Massar Website
    url: https://massar.men.gov.ma
    favicon: https://massar.men.gov.ma/favicon.ico
  - name: Massar Login
    url: https://massarservice.men.gov.ma/moutamadris/Account
    favicon: https://massar.men.gov.ma/favicon.ico


workflowSchedule:
  graphs: "*/10 * * * *"
  responseTime: "*/10 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/10 * * * *"
  updateTemplate: "*/10 * * * *"
  updates: "*/10 * * * *"
  uptime: "*/10 * * * *"
